### ISSUE TITLE
Report correct hostname for docker containers.

### ISSUE THREAD

**Issue by FrankvanMeeuwen** [raboof/connbeat#103]
Currently all docker containers discovered by connection beat report the hostname and local_ips of the docker container that connection beat is running in. In order to discover connections between docker containers this should be the local_ips of the docker container itself. 

The hostname that is reported is currently the hostname of the docker container, but perhaps this should be the hostname of the host that runs docker.

**Comment by raboof** [comment]
Indeed `local_ips` should be restricted to that docker container.

I'm not sure we can take the hostname from the container (this usually just is the container id, right?).

**Comment by FrankvanMeeuwen** [comment]
This hostname currently is usually the abbreviated docker container id, but can be different depending on the container. What i would like to suggest is to take the hostname of the machine running docker instead. (At least this would be more useful in StackState) I am not sure though if you can access that from inside a container.

**Comment by raboof** [comment]
Instead of the hostname the image name might be even more useful/descriptive, though, perhaps?

**Comment by raboof** [comment]
After some consideration this might not be relevant: it might be OK to report the beat 'hostname' as the beat, and solve relating the docker containers to the docker host in e.g. the mesos integration.
