### ISSUE TITLE
Support for detecting connections to ports published to the host of a docker container

### ISSUE THREAD

**Issue by FrankvanMeeuwen** [raboof/connbeat#104]
If a docker container publishes its port to the host machine, with the -p flag, or running in host network mode, a connection to that container cannot be discovered, because the host ip-address and the published port are used to connect to.

E.g. consider a docker container c1 listening on 172.17.0.1:10 on machine m1, that has published port 10 to its host on  192.168.2.38:80. Another docker container than can connect to 192.168.2.38:80, which gets forwarded to 172.17.0.1:10, but 192.168.2.38:10 is not registered with c1.

**Comment by raboof** [comment]
I don't think we support monitoring when using 'host networking' at all right now (but I could be wrong).

Exposing port mappings might indeed be interesting.

**Comment by raboof** [comment]
Port mappings has been done in #118
