### ISSUE TITLE
Connectionbeat does not report some connections

### ISSUE THREAD

**Issue by craffit** [raboof/connbeat#174]
A reproducible case can be found in the following docker container image: 508573134510.dkr.ecr.eu-west-1.amazonaws.com/bug-reports:connbeat_bug.

Steps to reproduce:
> docker run -it bug-reports:connbeat_bug bash
> ./start_services.sh
> lsof -i
COMMAND  PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
java    7343 root   28u  IPv6 59782685      0t0  TCP localhost:36124->localhost:8888 (ESTABLISHED)
java    7369 root   30u  IPv6 59782687      0t0  TCP localhost:36128->localhost:8888 (ESTABLISHED)
java    7458 root   27u  IPv6 59780886      0t0  TCP *:8888 (LISTEN)
java    7458 root   28u  IPv6 59783431      0t0  TCP localhost:8888->localhost:36124 (ESTABLISHED)
java    7458 root   31u  IPv6 59784340      0t0  TCP localhost:8888->localhost:36128 (ESTABLISHED)
> tail -f /var/log/stackstate/connbeat.out | grep 36128
<NOTHING APPEARS>

OBSERVED:
No connections are observed for one of the two processes. We have observed instances where a connection is reported, but only in one direction.

EXPECTED:
Connections in both directions should be reported by connbeat, for both processes.

**Comment by raboof** [comment]
I expect #176 solves this issue.
