### ISSUE TITLE
Connectionbeat does not report some existing containers

### ISSUE THREAD

**Issue by craffit** [raboof/connbeat#175]
Connectionbeat fails to report some of the containers that are running on the host.

The setup:

Connectionbeat running in a docker container with the socket mounted. 4 containers are spawned by mesos, but only 1 (sometimes two) is reported.

Logs:
[running_containers.txt](https://github.com/raboof/connbeat/files/747532/running_containers.txt)
[cb.txt](https://github.com/raboof/connbeat/files/747533/cb.txt)

**Comment by raboof** [comment]
As connbeat only reports on connections, not on containers, if a container does not have any connections it will not be reported.

If we want to collect information about containers independently from their connections I think we should use something like https://github.com/Ingensi/dockbeat
